---
<div style="text-align: center; font-family: 'Times New Roman', Times, serif;">
 <h1>Numpy</h1>
</div
>

<div id="badges" style="text-align: center; background-color: #333; padding: 10px; margin-bottom: 10px;">
    <a href="https://www.linkedin.com/feed/?trk=404_page" target="_blank" rel="noopener noreferrer">
        <img src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn Badge"/>
    </a>
</div>


<div id="badges" style="text-align: center; background-color: #333; padding: 10px; margin-bottom: 10px;">
    <a href="https://github.com/mshahzaib4/mshahzaib4" target="_blank" rel="noopener noreferrer">
        <img src="https://img.shields.io/badge/GitHub-181717?style=for-the-badge&logo=github&logoColor=white" alt="GitHub Badge"/>
    </a>
</div>

<div id="badges" style="text-align: center; background-color: #333; padding: 10px; margin-bottom: 10px;">
    <a href="https://www.kaggle.com/shahzaibmalik44" target="_blank" rel="noopener noreferrer">
        <img src="https://img.shields.io/badge/Kaggle-20BEFF?style=for-the-badge&logo=kaggle&logoColor=white" alt="Kaggle Badge"/>
    </a>
</div>

<p style="font-size: 20px;font-family:newtimeroman; color:; text-align: center; margin-left: 10px;">Notebook Author: Muhammad Shahzaib Yaqoob 
 <p>
 
---

NumPy is a Python library used for working with arrays. It also includes functions for operations in linear algebra, Fourier transform, and matrices. It is optimized for numerical computations, making it a key library for scientific computing and data analysis in Python.

<div style="font-family: 'Times New Roman', Times, serif;">
  <h3 style="text-align: center;">Types of Array</h3>
  <div style="margin-left: 4mm;">- 1D (One Dimensional Array)</div>
  <div style="margin-left: 4mm;">- 2D (Two Dimensional Array)</div>
  <div style="margin-left: 4mm;">- 3D (Three Dimensional)</div>


In [90]:
import numpy as np

In [91]:
Array_data=np.array([10,20,30,40,50,60])

In [92]:
Array_data

array([1, 2, 3, 4, 5, 6])

In [93]:
# 1D Array
Data_Array1=np.array([100,200,300,400,500,600])
Data_Array1

array([1, 2, 3, 4, 5, 6])

In [94]:
# 2D Array
data_Array2=np.array([[1,2,3,4,],[5,6,7,8]]) # create Array 2 X 2
data_Array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
# 3D Array
data_Array3 = np.array([[[1, 2, 3.4], [1, 2, 3.4], [1, 2, 3.4]],[[4, 5, 6.7], [4, 5, 6.7], [4, 5, 6.7]]])
data_Array3

array([[[1. , 2. , 3.4],
        [1. , 2. , 3.4],
        [1. , 2. , 3.4]],

       [[4. , 5. , 6.7],
        [4. , 5. , 6.7],
        [4. , 5. , 6.7]]])